apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: web
spec:
  containers:
    - name: demo
      image: eu.gcr.io/decem-242714/apache-empty:v.0.1
      ports:
        - containerPort: 80
      volumeMounts:
      - mountPath: /var/www/html/
        name: test-volume
  volumes:
  - name: test-volume
    gcePersistentDisk:
      pdName: mi-volumen
      fsType: ext4