apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-final-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-final
    spec:
      initContainers:
       - name: setup-database
         image: eu.gcr.io/decem-242714/app-final:v.0.1
         command: ["rails","db:create"]
         envFrom:
            - configMapRef:
                name: railsapp-configmap
         env:
            - name: "MYSQL_USER"
              valueFrom:
                secretKeyRef:
                  name: mysql-rails-secret
                  key: username
            - name: "MYSQL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: mysql-rails-secret
                  key: password
       - name: schema-migration
         image: eu.gcr.io/decem-242714/app-final:v.0.1
         command: ["rails","db:migrate"]
         envFrom:
            - configMapRef:
                name: railsapp-configmap
         env:
            - name: "MYSQL_USER"
              valueFrom:
                secretKeyRef:
                  name: mysql-rails-secret
                  key: username
            - name: "MYSQL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: mysql-rails-secret
                  key: password
      containers:
       - name: demo
         image: eu.gcr.io/decem-242714/app-final:v.0.1
         command: ["foreman","start","-f","Procfile.dev"]
         envFrom:
            - configMapRef:
                name: railsapp-configmap
         env:
            - name: "MYSQL_USER"
              valueFrom:
                secretKeyRef:
                  name: mysql-rails-secret
                  key: username
            - name: "MYSQL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: mysql-rails-secret
                  key: password
         ports:
            - containerPort: 5000
              name: foreman-port
         volumeMounts:
          - name: activestorage
            mountPath: /app/storage
         livenessProbe:
            httpGet:
              path: /monitoring/alive
              port: foreman-port
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
         readinessProbe:
            httpGet:
              path: /monitoring/ready
              port: foreman-port
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 15
      volumes:
        - name: activestorage
          persistentVolumeClaim:
            claimName: rails-activestorage-claim
