apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: readiness-app-test
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: firstapp
    spec:
      containers:
       - name: demo
         image: eu.gcr.io/decem-242714/node-host:v.0.1
         ports:
           - containerPort: 3000
             name: nodejs-port  
         livenessProbe:
             httpGet:
               path: /
               port: 3000
             initialDelaySeconds: 35
             timeoutSeconds: 30
         readinessProbe:
             httpGet:
               path: /
               port: 3000
             initialDelaySeconds: 15
             timeoutSeconds: 30 

