apiVersion: v1
data:
  charset.cnf: |
    [client]
    #Esta es mi config personalizada
    # Default is Latin1, if you need UTF-8 set this (also in server section)
    default-character-set = utf8 

    [mysqld]
    #
    # * Character sets
    #
    # Default is Latin1, if you need UTF-8 set all this (also in client section)
    #
    character-set-server  = utf8 
    collation-server      = utf8_unicode_ci
  new-database-name: my_database
kind: ConfigMap
metadata:
  name: mysql-configmap