apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-prod
  labels:
    app: database
    env: production
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: mysql-persistence-production
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-dev
  labels:
    app: database
    env: development
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: mysql-persistence-devel
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-claim
  labels:
    app: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  selector: 
    matchLabels: 
      app: database
      env: production