apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: cool-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cool-app
    spec:
      containers:
        - name: cool-app
          image: eu.gcr.io/project/container:v.0.1
          command: ["/start-app"]
          ports:
            - containerPort: 3453
          envFrom:
            - configMapRef:
                name: backend-config
