apiVersion: v1
kind: PersistentVolume
metadata:
  name: rails-storage
  labels:
    app: rails-app
    component: active-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: rails-activestorage-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rails-activestorage-claim
  labels:
    app: rails-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: rails-app
      component: active-storage