apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  password: ZG51ZWhFUkZBRWFjbmV4dTQ4MzdxNDE4M2U=
  username: cmFpbHNhcHAtdXNlcm5hbWU=
  root: ZG5ldWJhbGNFQUZSdmNhYTM4N2U5MWRBc2RhZXU=
