apiVersion: v1
kind: PersistentVolume
metadata:
  name: rails-database
  labels:
    app: rails-app
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: rails-database-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rails-db-claim
  labels:
    app: rails-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  selector: 
    matchLabels: 
      app: rails-app