apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: first-app-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: firstdeploy
    spec:
      containers:
       - name: demo
         image: eu.gcr.io/decem-242714/node-host:v.0.1
         ports:
           - containerPort: 3000
             name: nodejs-port  
