apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sinatra-app
  labels:
    app: sinatra
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sinatra
    spec:
      containers:
       - name: demo
         image: eu.gcr.io/decem-242714/sinatra:v.0.2
         ports:
            - containerPort: 4567
         envFrom:
            - configMapRef:
                name: backend-config
