apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: firstapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: nodejs-port
    nodePort: 32766