kubectl delete -f ../3.deployments/first-app-deployment.yaml
kubectl delete -f ../6.secrets/cool-app.yaml
kubectl delete -f ../9.configmaps/sinatra.yaml
kubectl delete -f ../11.app-final/mysql-configmap.yaml
kubectl delete -f ../11.app-final/mysql-secret.yaml
kubectl delete -f ../11.app-final/mysql-storage.yaml
kubectl delete -f ../11.app-final/mysql.yaml
kubectl delete -f ../11.app-final/app-config.yaml
kubectl delete -f ../11.app-final/app-storage.yaml
kubectl delete -f ../11.app-final/app.yaml
kubectl delete -f ./app-services.yaml